/**
 * <pre>
 * Copyright (c) 1995-2012 levigo holding gmbh. All Rights Reserved.
 *
 * This software is the proprietary information of levigo holding gmbh.
 * Use is subject to license terms.
 * </pre>
 */
/*
 * generated by Xtext
 */
package com.levigo.jadice.tools.pdf.modelgen;


/**
 * Use this class to register components to be used at runtime / without the
 * Equinox extension registry.
 */
public class PDFModelRuntimeModule extends
		com.levigo.jadice.tools.pdf.modelgen.AbstractPDFModelRuntimeModule {

}
