/*
* generated by Xtext
*/
package com.levigo.jadice.tools.pdf.modelgen.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import com.levigo.jadice.tools.pdf.modelgen.services.PDFModelGrammarAccess;

public class PDFModelParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private PDFModelGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected com.levigo.jadice.tools.pdf.modelgen.parser.antlr.internal.InternalPDFModelParser createParser(XtextTokenStream stream) {
		return new com.levigo.jadice.tools.pdf.modelgen.parser.antlr.internal.InternalPDFModelParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "PDFModel";
	}
	
	public PDFModelGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(PDFModelGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
