/*
* generated by Xtext
*/
package com.levigo.jadice.tools.pdf.modelgen.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class PDFModelAntlrTokenFileProvider implements IAntlrTokenFileProvider {
	
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
    	return classLoader.getResourceAsStream("com/levigo/jadice/tools/pdf/modelgen/parser/antlr/internal/InternalPDFModel.tokens");
	}
}
