/*
* generated by Xtext
*/
package com.levigo.jadice.tools.pdf.modelgen.validation;
 
import java.util.ArrayList;
import java.util.List;

import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.validation.ComposedChecks;

@ComposedChecks(validators= {org.eclipse.xtext.validation.NamesAreUniqueValidator.class})
public class AbstractPDFModelJavaValidator extends org.eclipse.xtext.validation.AbstractDeclarativeValidator {

	@Override
	protected List<EPackage> getEPackages() {
	    List<EPackage> result = new ArrayList<EPackage>();
	    result.add(com.levigo.jadice.tools.pdf.modelgen.pdfmodel.PdfmodelPackage.eINSTANCE);
		return result;
	}

}
