/*
* generated by Xtext
*/
package com.levigo.jadice.tools.pdf.modelgen.ui.contentassist.antlr;

import java.util.Collection;
import java.util.Map;
import java.util.HashMap;

import org.antlr.runtime.RecognitionException;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.AbstractContentAssistParser;
import org.eclipse.xtext.ui.editor.contentassist.antlr.FollowElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.internal.AbstractInternalContentAssistParser;

import com.google.inject.Inject;

import com.levigo.jadice.tools.pdf.modelgen.services.PDFModelGrammarAccess;

public class PDFModelParser extends AbstractContentAssistParser {
	
	@Inject
	private PDFModelGrammarAccess grammarAccess;
	
	private Map<AbstractElement, String> nameMappings;
	
	@Override
	protected com.levigo.jadice.tools.pdf.modelgen.ui.contentassist.antlr.internal.InternalPDFModelParser createParser() {
		com.levigo.jadice.tools.pdf.modelgen.ui.contentassist.antlr.internal.InternalPDFModelParser result = new com.levigo.jadice.tools.pdf.modelgen.ui.contentassist.antlr.internal.InternalPDFModelParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}
	
	@Override
	protected String getRuleName(AbstractElement element) {
		if (nameMappings == null) {
			nameMappings = new HashMap<AbstractElement, String>() {
				private static final long serialVersionUID = 1L;
				{
					put(grammarAccess.getAbstractDeclarationAccess().getAlternatives(), "rule__AbstractDeclaration__Alternatives");
					put(grammarAccess.getAbstractEntryAccess().getAlternatives(), "rule__AbstractEntry__Alternatives");
					put(grammarAccess.getDictionaryDeclarationAccess().getAlternatives_0(), "rule__DictionaryDeclaration__Alternatives_0");
					put(grammarAccess.getAbstractEntryValueAccess().getAlternatives(), "rule__AbstractEntryValue__Alternatives");
					put(grammarAccess.getNameObjectEntryValueAccess().getAlternatives_2(), "rule__NameObjectEntryValue__Alternatives_2");
					put(grammarAccess.getNumberObjectEntryValueAccess().getAlternatives_3(), "rule__NumberObjectEntryValue__Alternatives_3");
					put(grammarAccess.getNumberValidationRuleAccess().getAlternatives(), "rule__NumberValidationRule__Alternatives");
					put(grammarAccess.getIntegerObjectEntryValueAccess().getAlternatives_3(), "rule__IntegerObjectEntryValue__Alternatives_3");
					put(grammarAccess.getIntegerValidationRuleAccess().getAlternatives(), "rule__IntegerValidationRule__Alternatives");
					put(grammarAccess.getRealObjectEntryValueAccess().getAlternatives_2(), "rule__RealObjectEntryValue__Alternatives_2");
					put(grammarAccess.getStringEntryValueAccess().getAlternatives_0(), "rule__StringEntryValue__Alternatives_0");
					put(grammarAccess.getBooleanEntryValueAccess().getAlternatives_2(), "rule__BooleanEntryValue__Alternatives_2");
					put(grammarAccess.getNameEnumEntryValueAccess().getAlternatives_2(), "rule__NameEnumEntryValue__Alternatives_2");
					put(grammarAccess.getNumberLiteralAccess().getAlternatives(), "rule__NumberLiteral__Alternatives");
					put(grammarAccess.getIndirectReferenceAccess().getAlternatives(), "rule__IndirectReference__Alternatives");
					put(grammarAccess.getSinceVersionAccess().getAlternatives(), "rule__SinceVersion__Alternatives");
					put(grammarAccess.getBoolAccess().getAlternatives(), "rule__Bool__Alternatives");
					put(grammarAccess.getPDFModelAccess().getGroup(), "rule__PDFModel__Group__0");
					put(grammarAccess.getModelConfigAccess().getGroup(), "rule__ModelConfig__Group__0");
					put(grammarAccess.getCoreTypesConfigAccess().getGroup(), "rule__CoreTypesConfig__Group__0");
					put(grammarAccess.getSpecificationReferenceAccess().getGroup(), "rule__SpecificationReference__Group__0");
					put(grammarAccess.getSpecificationReferenceAccess().getGroup_4(), "rule__SpecificationReference__Group_4__0");
					put(grammarAccess.getSectionReferenceAccess().getGroup(), "rule__SectionReference__Group__0");
					put(grammarAccess.getArrayMappedDeclarationAccess().getGroup(), "rule__ArrayMappedDeclaration__Group__0");
					put(grammarAccess.getArrayMappedDeclarationAccess().getGroup_2(), "rule__ArrayMappedDeclaration__Group_2__0");
					put(grammarAccess.getArrayMappedEntryAccess().getGroup(), "rule__ArrayMappedEntry__Group__0");
					put(grammarAccess.getArrayMappedEntryAccess().getGroup_8(), "rule__ArrayMappedEntry__Group_8__0");
					put(grammarAccess.getDictionaryDeclarationAccess().getGroup(), "rule__DictionaryDeclaration__Group__0");
					put(grammarAccess.getDictionaryDeclarationAccess().getGroup_2(), "rule__DictionaryDeclaration__Group_2__0");
					put(grammarAccess.getDictionaryDeclarationAccess().getGroup_2_2(), "rule__DictionaryDeclaration__Group_2_2__0");
					put(grammarAccess.getDictionaryDeclarationAccess().getGroup_3(), "rule__DictionaryDeclaration__Group_3__0");
					put(grammarAccess.getDictionaryDeclarationAccess().getGroup_5(), "rule__DictionaryDeclaration__Group_5__0");
					put(grammarAccess.getSubtypeConfigAccess().getGroup(), "rule__SubtypeConfig__Group__0");
					put(grammarAccess.getSubtypeConfigAccess().getGroup_2(), "rule__SubtypeConfig__Group_2__0");
					put(grammarAccess.getDictionaryEntryAccess().getGroup(), "rule__DictionaryEntry__Group__0");
					put(grammarAccess.getDictionaryEntryAccess().getGroup_1(), "rule__DictionaryEntry__Group_1__0");
					put(grammarAccess.getDictionaryEntryAccess().getGroup_9(), "rule__DictionaryEntry__Group_9__0");
					put(grammarAccess.getPackageDeclarationAccess().getGroup(), "rule__PackageDeclaration__Group__0");
					put(grammarAccess.getBitFlagsDeclarationAccess().getGroup(), "rule__BitFlagsDeclaration__Group__0");
					put(grammarAccess.getBitFlagsDeclarationAccess().getGroup_3(), "rule__BitFlagsDeclaration__Group_3__0");
					put(grammarAccess.getBitFlagsDeclarationPartAccess().getGroup(), "rule__BitFlagsDeclarationPart__Group__0");
					put(grammarAccess.getBitFlagsDeclarationPartAccess().getGroup_3(), "rule__BitFlagsDeclarationPart__Group_3__0");
					put(grammarAccess.getNameEnumDeclarationAccess().getGroup(), "rule__NameEnumDeclaration__Group__0");
					put(grammarAccess.getNameEnumDeclarationAccess().getGroup_2(), "rule__NameEnumDeclaration__Group_2__0");
					put(grammarAccess.getNameEnumDeclarationAccess().getGroup_5(), "rule__NameEnumDeclaration__Group_5__0");
					put(grammarAccess.getNameEnumDeclarationPartAccess().getGroup(), "rule__NameEnumDeclarationPart__Group__0");
					put(grammarAccess.getNameEnumDeclarationPartAccess().getGroup_1(), "rule__NameEnumDeclarationPart__Group_1__0");
					put(grammarAccess.getNameEnumDeclarationPartAccess().getGroup_2(), "rule__NameEnumDeclarationPart__Group_2__0");
					put(grammarAccess.getNullObjectEntryValueAccess().getGroup(), "rule__NullObjectEntryValue__Group__0");
					put(grammarAccess.getNameObjectEntryValueAccess().getGroup(), "rule__NameObjectEntryValue__Group__0");
					put(grammarAccess.getNameObjectEntryValueAccess().getGroup_2_0(), "rule__NameObjectEntryValue__Group_2_0__0");
					put(grammarAccess.getNameObjectEntryValueAccess().getGroup_2_1(), "rule__NameObjectEntryValue__Group_2_1__0");
					put(grammarAccess.getNumberObjectEntryValueAccess().getGroup(), "rule__NumberObjectEntryValue__Group__0");
					put(grammarAccess.getNumberObjectEntryValueAccess().getGroup_2(), "rule__NumberObjectEntryValue__Group_2__0");
					put(grammarAccess.getNumberObjectEntryValueAccess().getGroup_3_0(), "rule__NumberObjectEntryValue__Group_3_0__0");
					put(grammarAccess.getNumberObjectEntryValueAccess().getGroup_3_1(), "rule__NumberObjectEntryValue__Group_3_1__0");
					put(grammarAccess.getNumberInclusiveRangeValidationRuleAccess().getGroup(), "rule__NumberInclusiveRangeValidationRule__Group__0");
					put(grammarAccess.getNumberGreaterValidationRuleAccess().getGroup(), "rule__NumberGreaterValidationRule__Group__0");
					put(grammarAccess.getNumberGreaterEqualsValidationRuleAccess().getGroup(), "rule__NumberGreaterEqualsValidationRule__Group__0");
					put(grammarAccess.getNumberValuesValidationRuleAccess().getGroup(), "rule__NumberValuesValidationRule__Group__0");
					put(grammarAccess.getNumberValuesValidationRuleAccess().getGroup_2(), "rule__NumberValuesValidationRule__Group_2__0");
					put(grammarAccess.getNumberValuesValidationRuleEntryAccess().getGroup(), "rule__NumberValuesValidationRuleEntry__Group__0");
					put(grammarAccess.getNumberValuesValidationRuleEntryAccess().getGroup_1(), "rule__NumberValuesValidationRuleEntry__Group_1__0");
					put(grammarAccess.getIntegerObjectEntryValueAccess().getGroup(), "rule__IntegerObjectEntryValue__Group__0");
					put(grammarAccess.getIntegerObjectEntryValueAccess().getGroup_2(), "rule__IntegerObjectEntryValue__Group_2__0");
					put(grammarAccess.getIntegerObjectEntryValueAccess().getGroup_3_0(), "rule__IntegerObjectEntryValue__Group_3_0__0");
					put(grammarAccess.getIntegerObjectEntryValueAccess().getGroup_3_1(), "rule__IntegerObjectEntryValue__Group_3_1__0");
					put(grammarAccess.getIntegerInclusiveRangeValidationRuleAccess().getGroup(), "rule__IntegerInclusiveRangeValidationRule__Group__0");
					put(grammarAccess.getIntegerValuesValidationRuleAccess().getGroup(), "rule__IntegerValuesValidationRule__Group__0");
					put(grammarAccess.getIntegerValuesValidationRuleAccess().getGroup_2(), "rule__IntegerValuesValidationRule__Group_2__0");
					put(grammarAccess.getIntegerGreaterValidationRuleAccess().getGroup(), "rule__IntegerGreaterValidationRule__Group__0");
					put(grammarAccess.getIntegerGreaterEqualsValidationRuleAccess().getGroup(), "rule__IntegerGreaterEqualsValidationRule__Group__0");
					put(grammarAccess.getIntegerValuesValidationRuleEntryAccess().getGroup(), "rule__IntegerValuesValidationRuleEntry__Group__0");
					put(grammarAccess.getIntegerValuesValidationRuleEntryAccess().getGroup_1(), "rule__IntegerValuesValidationRuleEntry__Group_1__0");
					put(grammarAccess.getRealObjectEntryValueAccess().getGroup(), "rule__RealObjectEntryValue__Group__0");
					put(grammarAccess.getRealObjectEntryValueAccess().getGroup_2_0(), "rule__RealObjectEntryValue__Group_2_0__0");
					put(grammarAccess.getRealObjectEntryValueAccess().getGroup_2_1(), "rule__RealObjectEntryValue__Group_2_1__0");
					put(grammarAccess.getNameTreeEntryValueAccess().getGroup(), "rule__NameTreeEntryValue__Group__0");
					put(grammarAccess.getNumberTreeEntryValueAccess().getGroup(), "rule__NumberTreeEntryValue__Group__0");
					put(grammarAccess.getArrayEntryValueAccess().getGroup(), "rule__ArrayEntryValue__Group__0");
					put(grammarAccess.getArrayEntryValueAccess().getGroup_1(), "rule__ArrayEntryValue__Group_1__0");
					put(grammarAccess.getArrayLengthValidationRuleAccess().getGroup(), "rule__ArrayLengthValidationRule__Group__0");
					put(grammarAccess.getObjectEntryValueAccess().getGroup(), "rule__ObjectEntryValue__Group__0");
					put(grammarAccess.getMappingDictEntryValueAccess().getGroup(), "rule__MappingDictEntryValue__Group__0");
					put(grammarAccess.getStringEntryValueAccess().getGroup(), "rule__StringEntryValue__Group__0");
					put(grammarAccess.getStringEntryValueAccess().getGroup_1(), "rule__StringEntryValue__Group_1__0");
					put(grammarAccess.getStringLengthValidationRuleAccess().getGroup(), "rule__StringLengthValidationRule__Group__0");
					put(grammarAccess.getAlternativeEntryValueAccess().getGroup(), "rule__AlternativeEntryValue__Group__0");
					put(grammarAccess.getAlternativeEntryValueAccess().getGroup_2(), "rule__AlternativeEntryValue__Group_2__0");
					put(grammarAccess.getBooleanEntryValueAccess().getGroup(), "rule__BooleanEntryValue__Group__0");
					put(grammarAccess.getBooleanEntryValueAccess().getGroup_2_0(), "rule__BooleanEntryValue__Group_2_0__0");
					put(grammarAccess.getBooleanEntryValueAccess().getGroup_2_1(), "rule__BooleanEntryValue__Group_2_1__0");
					put(grammarAccess.getReferenceEntryValueAccess().getGroup(), "rule__ReferenceEntryValue__Group__0");
					put(grammarAccess.getParentReferenceEntryValueAccess().getGroup(), "rule__ParentReferenceEntryValue__Group__0");
					put(grammarAccess.getDictionaryObjectEntryValueAccess().getGroup(), "rule__DictionaryObjectEntryValue__Group__0");
					put(grammarAccess.getDictionaryDeclarationEntryValueAccess().getGroup(), "rule__DictionaryDeclarationEntryValue__Group__0");
					put(grammarAccess.getArrayMappedEntryValueAccess().getGroup(), "rule__ArrayMappedEntryValue__Group__0");
					put(grammarAccess.getBitFlagsEntryValueAccess().getGroup(), "rule__BitFlagsEntryValue__Group__0");
					put(grammarAccess.getDateEntryValueAccess().getGroup(), "rule__DateEntryValue__Group__0");
					put(grammarAccess.getNameEnumEntryValueAccess().getGroup(), "rule__NameEnumEntryValue__Group__0");
					put(grammarAccess.getNameEnumEntryValueAccess().getGroup_2_0(), "rule__NameEnumEntryValue__Group_2_0__0");
					put(grammarAccess.getNameEnumEntryValueAccess().getGroup_2_1(), "rule__NameEnumEntryValue__Group_2_1__0");
					put(grammarAccess.getQualifiedNameAccess().getGroup(), "rule__QualifiedName__Group__0");
					put(grammarAccess.getQualifiedNameAccess().getGroup_1(), "rule__QualifiedName__Group_1__0");
					put(grammarAccess.getPDFModelAccess().getConfigAssignment_0(), "rule__PDFModel__ConfigAssignment_0");
					put(grammarAccess.getPDFModelAccess().getPackagesAssignment_1(), "rule__PDFModel__PackagesAssignment_1");
					put(grammarAccess.getModelConfigAccess().getBasePackageAssignment_3(), "rule__ModelConfig__BasePackageAssignment_3");
					put(grammarAccess.getModelConfigAccess().getCoreTypesConfigAssignment_5(), "rule__ModelConfig__CoreTypesConfigAssignment_5");
					put(grammarAccess.getCoreTypesConfigAccess().getObjectTypeNameAssignment_3(), "rule__CoreTypesConfig__ObjectTypeNameAssignment_3");
					put(grammarAccess.getCoreTypesConfigAccess().getReferenceTypeNameAssignment_6(), "rule__CoreTypesConfig__ReferenceTypeNameAssignment_6");
					put(grammarAccess.getCoreTypesConfigAccess().getDictionaryTypeNameAssignment_9(), "rule__CoreTypesConfig__DictionaryTypeNameAssignment_9");
					put(grammarAccess.getCoreTypesConfigAccess().getNameTypeNameAssignment_12(), "rule__CoreTypesConfig__NameTypeNameAssignment_12");
					put(grammarAccess.getCoreTypesConfigAccess().getStringTypeNameAssignment_15(), "rule__CoreTypesConfig__StringTypeNameAssignment_15");
					put(grammarAccess.getCoreTypesConfigAccess().getLiteralStringTypeNameAssignment_18(), "rule__CoreTypesConfig__LiteralStringTypeNameAssignment_18");
					put(grammarAccess.getCoreTypesConfigAccess().getHexStringTypeNameAssignment_21(), "rule__CoreTypesConfig__HexStringTypeNameAssignment_21");
					put(grammarAccess.getCoreTypesConfigAccess().getArrayTypeNameAssignment_24(), "rule__CoreTypesConfig__ArrayTypeNameAssignment_24");
					put(grammarAccess.getCoreTypesConfigAccess().getBooleanTypeNameAssignment_27(), "rule__CoreTypesConfig__BooleanTypeNameAssignment_27");
					put(grammarAccess.getCoreTypesConfigAccess().getNumberTypeNameAssignment_30(), "rule__CoreTypesConfig__NumberTypeNameAssignment_30");
					put(grammarAccess.getCoreTypesConfigAccess().getRealTypeNameAssignment_33(), "rule__CoreTypesConfig__RealTypeNameAssignment_33");
					put(grammarAccess.getCoreTypesConfigAccess().getIntegerTypeNameAssignment_36(), "rule__CoreTypesConfig__IntegerTypeNameAssignment_36");
					put(grammarAccess.getCoreTypesConfigAccess().getNullTypeNameAssignment_39(), "rule__CoreTypesConfig__NullTypeNameAssignment_39");
					put(grammarAccess.getCoreTypesConfigAccess().getStreamTypeNameAssignment_42(), "rule__CoreTypesConfig__StreamTypeNameAssignment_42");
					put(grammarAccess.getCoreTypesConfigAccess().getNameTreeTypeNameAssignment_48(), "rule__CoreTypesConfig__NameTreeTypeNameAssignment_48");
					put(grammarAccess.getCoreTypesConfigAccess().getNumberTreeTypeNameAssignment_51(), "rule__CoreTypesConfig__NumberTreeTypeNameAssignment_51");
					put(grammarAccess.getCoreTypesConfigAccess().getNameTreeParserTypeNameAssignment_54(), "rule__CoreTypesConfig__NameTreeParserTypeNameAssignment_54");
					put(grammarAccess.getCoreTypesConfigAccess().getNumberTreeParserTypeNameAssignment_57(), "rule__CoreTypesConfig__NumberTreeParserTypeNameAssignment_57");
					put(grammarAccess.getSpecificationReferenceAccess().getSectionAssignment_3(), "rule__SpecificationReference__SectionAssignment_3");
					put(grammarAccess.getSpecificationReferenceAccess().getTableAssignment_4_2(), "rule__SpecificationReference__TableAssignment_4_2");
					put(grammarAccess.getSectionReferenceAccess().getSectionAssignment_1(), "rule__SectionReference__SectionAssignment_1");
					put(grammarAccess.getArrayMappedDeclarationAccess().getNameAssignment_1(), "rule__ArrayMappedDeclaration__NameAssignment_1");
					put(grammarAccess.getArrayMappedDeclarationAccess().getSinceAssignment_2_1(), "rule__ArrayMappedDeclaration__SinceAssignment_2_1");
					put(grammarAccess.getArrayMappedDeclarationAccess().getEntriesAssignment_4(), "rule__ArrayMappedDeclaration__EntriesAssignment_4");
					put(grammarAccess.getArrayMappedEntryAccess().getIndexAssignment_0(), "rule__ArrayMappedEntry__IndexAssignment_0");
					put(grammarAccess.getArrayMappedEntryAccess().getNameAssignment_2(), "rule__ArrayMappedEntry__NameAssignment_2");
					put(grammarAccess.getArrayMappedEntryAccess().getCachedAssignment_3(), "rule__ArrayMappedEntry__CachedAssignment_3");
					put(grammarAccess.getArrayMappedEntryAccess().getRequiredAssignment_4(), "rule__ArrayMappedEntry__RequiredAssignment_4");
					put(grammarAccess.getArrayMappedEntryAccess().getNullableAssignment_5(), "rule__ArrayMappedEntry__NullableAssignment_5");
					put(grammarAccess.getArrayMappedEntryAccess().getIndirectReferenceAssignment_6(), "rule__ArrayMappedEntry__IndirectReferenceAssignment_6");
					put(grammarAccess.getArrayMappedEntryAccess().getValueAssignment_7(), "rule__ArrayMappedEntry__ValueAssignment_7");
					put(grammarAccess.getArrayMappedEntryAccess().getSinceAssignment_8_1(), "rule__ArrayMappedEntry__SinceAssignment_8_1");
					put(grammarAccess.getArrayMappedEntryAccess().getRequiresCustomValidationAssignment_9(), "rule__ArrayMappedEntry__RequiresCustomValidationAssignment_9");
					put(grammarAccess.getArrayMappedEntryAccess().getRequiresCustomDefaultAssignment_10(), "rule__ArrayMappedEntry__RequiresCustomDefaultAssignment_10");
					put(grammarAccess.getDictionaryDeclarationAccess().getStreamAssignment_0_1(), "rule__DictionaryDeclaration__StreamAssignment_0_1");
					put(grammarAccess.getDictionaryDeclarationAccess().getNameAssignment_1(), "rule__DictionaryDeclaration__NameAssignment_1");
					put(grammarAccess.getDictionaryDeclarationAccess().getSuperTypesAssignment_2_1(), "rule__DictionaryDeclaration__SuperTypesAssignment_2_1");
					put(grammarAccess.getDictionaryDeclarationAccess().getSuperTypesAssignment_2_2_1(), "rule__DictionaryDeclaration__SuperTypesAssignment_2_2_1");
					put(grammarAccess.getDictionaryDeclarationAccess().getSinceAssignment_3_1(), "rule__DictionaryDeclaration__SinceAssignment_3_1");
					put(grammarAccess.getDictionaryDeclarationAccess().getSubtypeConfigAssignment_5_2(), "rule__DictionaryDeclaration__SubtypeConfigAssignment_5_2");
					put(grammarAccess.getDictionaryDeclarationAccess().getEntriesAssignment_6(), "rule__DictionaryDeclaration__EntriesAssignment_6");
					put(grammarAccess.getSubtypeConfigAccess().getCandidatesAssignment_1(), "rule__SubtypeConfig__CandidatesAssignment_1");
					put(grammarAccess.getSubtypeConfigAccess().getCandidatesAssignment_2_1(), "rule__SubtypeConfig__CandidatesAssignment_2_1");
					put(grammarAccess.getDictionaryEntryAccess().getKeyAssignment_0(), "rule__DictionaryEntry__KeyAssignment_0");
					put(grammarAccess.getDictionaryEntryAccess().getAliasAssignment_1_1(), "rule__DictionaryEntry__AliasAssignment_1_1");
					put(grammarAccess.getDictionaryEntryAccess().getCachedAssignment_2(), "rule__DictionaryEntry__CachedAssignment_2");
					put(grammarAccess.getDictionaryEntryAccess().getRequiredAssignment_3(), "rule__DictionaryEntry__RequiredAssignment_3");
					put(grammarAccess.getDictionaryEntryAccess().getInheritableAssignment_4(), "rule__DictionaryEntry__InheritableAssignment_4");
					put(grammarAccess.getDictionaryEntryAccess().getIndirectReferenceAssignment_5(), "rule__DictionaryEntry__IndirectReferenceAssignment_5");
					put(grammarAccess.getDictionaryEntryAccess().getValueAssignment_6(), "rule__DictionaryEntry__ValueAssignment_6");
					put(grammarAccess.getDictionaryEntryAccess().getRequiresCustomValidationAssignment_7(), "rule__DictionaryEntry__RequiresCustomValidationAssignment_7");
					put(grammarAccess.getDictionaryEntryAccess().getRequiresCustomDefaultAssignment_8(), "rule__DictionaryEntry__RequiresCustomDefaultAssignment_8");
					put(grammarAccess.getDictionaryEntryAccess().getSinceAssignment_9_1(), "rule__DictionaryEntry__SinceAssignment_9_1");
					put(grammarAccess.getPackageDeclarationAccess().getNameAssignment_1(), "rule__PackageDeclaration__NameAssignment_1");
					put(grammarAccess.getPackageDeclarationAccess().getElementsAssignment_3(), "rule__PackageDeclaration__ElementsAssignment_3");
					put(grammarAccess.getBitFlagsDeclarationAccess().getSpecificationReferenceAssignment_0(), "rule__BitFlagsDeclaration__SpecificationReferenceAssignment_0");
					put(grammarAccess.getBitFlagsDeclarationAccess().getNameAssignment_2(), "rule__BitFlagsDeclaration__NameAssignment_2");
					put(grammarAccess.getBitFlagsDeclarationAccess().getSinceAssignment_3_1(), "rule__BitFlagsDeclaration__SinceAssignment_3_1");
					put(grammarAccess.getBitFlagsDeclarationAccess().getDeclarationsAssignment_5(), "rule__BitFlagsDeclaration__DeclarationsAssignment_5");
					put(grammarAccess.getBitFlagsDeclarationPartAccess().getIndexAssignment_0(), "rule__BitFlagsDeclarationPart__IndexAssignment_0");
					put(grammarAccess.getBitFlagsDeclarationPartAccess().getNameAssignment_2(), "rule__BitFlagsDeclarationPart__NameAssignment_2");
					put(grammarAccess.getBitFlagsDeclarationPartAccess().getSinceAssignment_3_1(), "rule__BitFlagsDeclarationPart__SinceAssignment_3_1");
					put(grammarAccess.getNameEnumDeclarationAccess().getNameAssignment_1(), "rule__NameEnumDeclaration__NameAssignment_1");
					put(grammarAccess.getNameEnumDeclarationAccess().getSinceAssignment_2_1(), "rule__NameEnumDeclaration__SinceAssignment_2_1");
					put(grammarAccess.getNameEnumDeclarationAccess().getDeclarationsAssignment_4(), "rule__NameEnumDeclaration__DeclarationsAssignment_4");
					put(grammarAccess.getNameEnumDeclarationAccess().getDeclarationsAssignment_5_1(), "rule__NameEnumDeclaration__DeclarationsAssignment_5_1");
					put(grammarAccess.getNameEnumDeclarationPartAccess().getConstantAssignment_0(), "rule__NameEnumDeclarationPart__ConstantAssignment_0");
					put(grammarAccess.getNameEnumDeclarationPartAccess().getAliasAssignment_1_1(), "rule__NameEnumDeclarationPart__AliasAssignment_1_1");
					put(grammarAccess.getNameEnumDeclarationPartAccess().getSinceAssignment_2_1(), "rule__NameEnumDeclarationPart__SinceAssignment_2_1");
					put(grammarAccess.getNameObjectEntryValueAccess().getHasMustBeAssignment_2_0_0(), "rule__NameObjectEntryValue__HasMustBeAssignment_2_0_0");
					put(grammarAccess.getNameObjectEntryValueAccess().getRequiredValueAssignment_2_0_1(), "rule__NameObjectEntryValue__RequiredValueAssignment_2_0_1");
					put(grammarAccess.getNameObjectEntryValueAccess().getHasDefaultAssignment_2_1_0(), "rule__NameObjectEntryValue__HasDefaultAssignment_2_1_0");
					put(grammarAccess.getNameObjectEntryValueAccess().getDefaultValueAssignment_2_1_1(), "rule__NameObjectEntryValue__DefaultValueAssignment_2_1_1");
					put(grammarAccess.getNumberObjectEntryValueAccess().getRuleAssignment_2_1(), "rule__NumberObjectEntryValue__RuleAssignment_2_1");
					put(grammarAccess.getNumberObjectEntryValueAccess().getHasMustBeAssignment_3_0_0(), "rule__NumberObjectEntryValue__HasMustBeAssignment_3_0_0");
					put(grammarAccess.getNumberObjectEntryValueAccess().getRequiredValueAssignment_3_0_1(), "rule__NumberObjectEntryValue__RequiredValueAssignment_3_0_1");
					put(grammarAccess.getNumberObjectEntryValueAccess().getHasDefaultAssignment_3_1_0(), "rule__NumberObjectEntryValue__HasDefaultAssignment_3_1_0");
					put(grammarAccess.getNumberObjectEntryValueAccess().getDefaultValueAssignment_3_1_1(), "rule__NumberObjectEntryValue__DefaultValueAssignment_3_1_1");
					put(grammarAccess.getNumberInclusiveRangeValidationRuleAccess().getLowerBoundAssignment_1(), "rule__NumberInclusiveRangeValidationRule__LowerBoundAssignment_1");
					put(grammarAccess.getNumberInclusiveRangeValidationRuleAccess().getUpperBoundAssignment_3(), "rule__NumberInclusiveRangeValidationRule__UpperBoundAssignment_3");
					put(grammarAccess.getNumberGreaterValidationRuleAccess().getMinValueAssignment_1(), "rule__NumberGreaterValidationRule__MinValueAssignment_1");
					put(grammarAccess.getNumberGreaterEqualsValidationRuleAccess().getMinValueAssignment_1(), "rule__NumberGreaterEqualsValidationRule__MinValueAssignment_1");
					put(grammarAccess.getNumberValuesValidationRuleAccess().getValueAssignment_1(), "rule__NumberValuesValidationRule__ValueAssignment_1");
					put(grammarAccess.getNumberValuesValidationRuleAccess().getValueAssignment_2_1(), "rule__NumberValuesValidationRule__ValueAssignment_2_1");
					put(grammarAccess.getNumberValuesValidationRuleEntryAccess().getValueAssignment_0(), "rule__NumberValuesValidationRuleEntry__ValueAssignment_0");
					put(grammarAccess.getNumberValuesValidationRuleEntryAccess().getSinceAssignment_1_1(), "rule__NumberValuesValidationRuleEntry__SinceAssignment_1_1");
					put(grammarAccess.getIntegerObjectEntryValueAccess().getRuleAssignment_2_1(), "rule__IntegerObjectEntryValue__RuleAssignment_2_1");
					put(grammarAccess.getIntegerObjectEntryValueAccess().getHasMustBeAssignment_3_0_0(), "rule__IntegerObjectEntryValue__HasMustBeAssignment_3_0_0");
					put(grammarAccess.getIntegerObjectEntryValueAccess().getRequiredValueAssignment_3_0_1(), "rule__IntegerObjectEntryValue__RequiredValueAssignment_3_0_1");
					put(grammarAccess.getIntegerObjectEntryValueAccess().getHasDefaultAssignment_3_1_0(), "rule__IntegerObjectEntryValue__HasDefaultAssignment_3_1_0");
					put(grammarAccess.getIntegerObjectEntryValueAccess().getDefaultValueAssignment_3_1_1(), "rule__IntegerObjectEntryValue__DefaultValueAssignment_3_1_1");
					put(grammarAccess.getIntegerInclusiveRangeValidationRuleAccess().getLowerBoundAssignment_1(), "rule__IntegerInclusiveRangeValidationRule__LowerBoundAssignment_1");
					put(grammarAccess.getIntegerInclusiveRangeValidationRuleAccess().getUpperBoundAssignment_3(), "rule__IntegerInclusiveRangeValidationRule__UpperBoundAssignment_3");
					put(grammarAccess.getIntegerValuesValidationRuleAccess().getValueAssignment_1(), "rule__IntegerValuesValidationRule__ValueAssignment_1");
					put(grammarAccess.getIntegerValuesValidationRuleAccess().getValueAssignment_2_1(), "rule__IntegerValuesValidationRule__ValueAssignment_2_1");
					put(grammarAccess.getIntegerGreaterValidationRuleAccess().getMinValueAssignment_1(), "rule__IntegerGreaterValidationRule__MinValueAssignment_1");
					put(grammarAccess.getIntegerGreaterEqualsValidationRuleAccess().getMinValueAssignment_1(), "rule__IntegerGreaterEqualsValidationRule__MinValueAssignment_1");
					put(grammarAccess.getIntegerValuesValidationRuleEntryAccess().getValueAssignment_0(), "rule__IntegerValuesValidationRuleEntry__ValueAssignment_0");
					put(grammarAccess.getIntegerValuesValidationRuleEntryAccess().getSinceAssignment_1_1(), "rule__IntegerValuesValidationRuleEntry__SinceAssignment_1_1");
					put(grammarAccess.getRealObjectEntryValueAccess().getHasMustBeAssignment_2_0_0(), "rule__RealObjectEntryValue__HasMustBeAssignment_2_0_0");
					put(grammarAccess.getRealObjectEntryValueAccess().getRequiredValueAssignment_2_0_1(), "rule__RealObjectEntryValue__RequiredValueAssignment_2_0_1");
					put(grammarAccess.getRealObjectEntryValueAccess().getHasDefaultAssignment_2_1_0(), "rule__RealObjectEntryValue__HasDefaultAssignment_2_1_0");
					put(grammarAccess.getRealObjectEntryValueAccess().getDefaultValueAssignment_2_1_1(), "rule__RealObjectEntryValue__DefaultValueAssignment_2_1_1");
					put(grammarAccess.getArrayEntryValueAccess().getRuleAssignment_1_1(), "rule__ArrayEntryValue__RuleAssignment_1_1");
					put(grammarAccess.getArrayEntryValueAccess().getIndirectReferenceAssignment_3(), "rule__ArrayEntryValue__IndirectReferenceAssignment_3");
					put(grammarAccess.getArrayEntryValueAccess().getTypeAssignment_4(), "rule__ArrayEntryValue__TypeAssignment_4");
					put(grammarAccess.getArrayEntryValueAccess().getRequiresCustomValidationAssignment_5(), "rule__ArrayEntryValue__RequiresCustomValidationAssignment_5");
					put(grammarAccess.getArrayEntryValueAccess().getRequiresCustomDefaultAssignment_6(), "rule__ArrayEntryValue__RequiresCustomDefaultAssignment_6");
					put(grammarAccess.getArrayLengthValidationRuleAccess().getLengthAssignment_1(), "rule__ArrayLengthValidationRule__LengthAssignment_1");
					put(grammarAccess.getMappingDictEntryValueAccess().getTypeAssignment_2(), "rule__MappingDictEntryValue__TypeAssignment_2");
					put(grammarAccess.getMappingDictEntryValueAccess().getRequiresCustomValidationAssignment_3(), "rule__MappingDictEntryValue__RequiresCustomValidationAssignment_3");
					put(grammarAccess.getMappingDictEntryValueAccess().getRequiresCustomDefaultAssignment_4(), "rule__MappingDictEntryValue__RequiresCustomDefaultAssignment_4");
					put(grammarAccess.getStringEntryValueAccess().getTextStringAssignment_0_0(), "rule__StringEntryValue__TextStringAssignment_0_0");
					put(grammarAccess.getStringEntryValueAccess().getAsciiStringAssignment_0_1(), "rule__StringEntryValue__AsciiStringAssignment_0_1");
					put(grammarAccess.getStringEntryValueAccess().getByteStringAssignment_0_2(), "rule__StringEntryValue__ByteStringAssignment_0_2");
					put(grammarAccess.getStringEntryValueAccess().getRuleAssignment_1_1(), "rule__StringEntryValue__RuleAssignment_1_1");
					put(grammarAccess.getStringLengthValidationRuleAccess().getLengthAssignment_1(), "rule__StringLengthValidationRule__LengthAssignment_1");
					put(grammarAccess.getAlternativeEntryValueAccess().getOptionsAssignment_1(), "rule__AlternativeEntryValue__OptionsAssignment_1");
					put(grammarAccess.getAlternativeEntryValueAccess().getOptionsAssignment_2_1(), "rule__AlternativeEntryValue__OptionsAssignment_2_1");
					put(grammarAccess.getBooleanEntryValueAccess().getHasMustBeAssignment_2_0_0(), "rule__BooleanEntryValue__HasMustBeAssignment_2_0_0");
					put(grammarAccess.getBooleanEntryValueAccess().getRequiredValueAssignment_2_0_1(), "rule__BooleanEntryValue__RequiredValueAssignment_2_0_1");
					put(grammarAccess.getBooleanEntryValueAccess().getHasDefaultAssignment_2_1_0(), "rule__BooleanEntryValue__HasDefaultAssignment_2_1_0");
					put(grammarAccess.getBooleanEntryValueAccess().getDefaultValueAssignment_2_1_1(), "rule__BooleanEntryValue__DefaultValueAssignment_2_1_1");
					put(grammarAccess.getParentReferenceEntryValueAccess().getParentTypeAssignment_1(), "rule__ParentReferenceEntryValue__ParentTypeAssignment_1");
					put(grammarAccess.getDictionaryDeclarationEntryValueAccess().getTargetAssignment_1(), "rule__DictionaryDeclarationEntryValue__TargetAssignment_1");
					put(grammarAccess.getArrayMappedEntryValueAccess().getTargetAssignment_1(), "rule__ArrayMappedEntryValue__TargetAssignment_1");
					put(grammarAccess.getBitFlagsEntryValueAccess().getTargetAssignment_1(), "rule__BitFlagsEntryValue__TargetAssignment_1");
					put(grammarAccess.getNameEnumEntryValueAccess().getTargetAssignment_1(), "rule__NameEnumEntryValue__TargetAssignment_1");
					put(grammarAccess.getNameEnumEntryValueAccess().getHasMustBeAssignment_2_0_0(), "rule__NameEnumEntryValue__HasMustBeAssignment_2_0_0");
					put(grammarAccess.getNameEnumEntryValueAccess().getRequiredValueAssignment_2_0_1(), "rule__NameEnumEntryValue__RequiredValueAssignment_2_0_1");
					put(grammarAccess.getNameEnumEntryValueAccess().getHasDefaultAssignment_2_1_0(), "rule__NameEnumEntryValue__HasDefaultAssignment_2_1_0");
					put(grammarAccess.getNameEnumEntryValueAccess().getDefaultValueAssignment_2_1_1(), "rule__NameEnumEntryValue__DefaultValueAssignment_2_1_1");
					put(grammarAccess.getIntLiteralAccess().getValueAssignment(), "rule__IntLiteral__ValueAssignment");
					put(grammarAccess.getRealLiteralAccess().getValueAssignment(), "rule__RealLiteral__ValueAssignment");
				}
			};
		}
		return nameMappings.get(element);
	}
	
	@Override
	protected Collection<FollowElement> getFollowElements(AbstractInternalContentAssistParser parser) {
		try {
			com.levigo.jadice.tools.pdf.modelgen.ui.contentassist.antlr.internal.InternalPDFModelParser typedParser = (com.levigo.jadice.tools.pdf.modelgen.ui.contentassist.antlr.internal.InternalPDFModelParser) parser;
			typedParser.entryRulePDFModel();
			return typedParser.getFollowElements();
		} catch(RecognitionException ex) {
			throw new RuntimeException(ex);
		}		
	}
	
	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}
	
	public PDFModelGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(PDFModelGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
