/*
 * generated by Xtext
 */
package com.levigo.jadice.tools.pdf.modelgen.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import com.levigo.jadice.tools.pdf.modelgen.ui.internal.PDFModelActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class PDFModelExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return PDFModelActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return PDFModelActivator.getInstance().getInjector(PDFModelActivator.COM_LEVIGO_JADICE_TOOLS_PDF_MODELGEN_PDFMODEL);
	}
	
}
