/**
 * <pre>
 * Copyright (c) 1995-2012 levigo holding gmbh. All Rights Reserved.
 *
 * This software is the proprietary information of levigo holding gmbh.
 * Use is subject to license terms.
 * </pre>
 */
/*
 * generated by Xtext
 */
package com.levigo.jadice.tools.pdf.modelgen.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class PDFModelUiModule extends com.levigo.jadice.tools.pdf.modelgen.ui.AbstractPDFModelUiModule {
	public PDFModelUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
